<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <style type="text/css">
      *{
        margin:0;
        padding:0;
      }
      body{
        background-image:url(https://img-cdn.inc.com/image/upload/w_1920,h_1080,c_fill/images/panoramic/GettyImages-1064877364_472283_mbievf.jpg);
        background-position:center;
        background-size:cover;
        font-family:sans-serif;
        margin-top:40px;
      }
      .regform{
        width:800px;
        background-color:rgb(0,0,0,0.6);
        margin:auto;
        color:#FFFFFF;
        padding:10px;
        text-align:center;
        border-radius:15px 15px 0px 0px;
      }
      .main{
        background-color:rgb(0,0,0,0.5);
        width:800px;
        margin:auto;
      }
      form{
        padding:10px;
      }

    .button{
      font-size:25px;
    background-color:#3BAF9F;
    display:block;
    margin:auto;
    text-align:center;
    border-radius:12px;
    border:2px solid #366473;
    padding:23px 90px;
    outline:none;
    color:white;
    cursor:pointer;
    transition:0.5px;
    }
    button:hover{
      background-color:black;
    }
    h1 {
      margin: 30px;
      font-family:Sans-serif;
      text-shadow: 5px 0 black;
      font-size: 4rem;
      color: black;
    }
    </style>
  </head>
  <body>
    <div class="regform">
      <h1>WELCOME ADMIN</h1>
    </div>
    <div class="main"></form>
        <br><br>
      <form method="post" action="emp_master.html">
          <button class="button" type="submit"  >ADD NEW EMPLOYEEE</button><br><br>
    </form>
        <form method="post" action="grade.html">
            <button class="button" type="submit">ADD EMPLOYEE GRADE</button><br><br>
        </form>
        <form method="post" action="salary.html">
            <button class="button" type="submit">SALARY DETAILS PAGE</button><br><br>
        </form>
      </form>
    </div>
  </body>
</html>
